builds:
  - id: hapesay
    dir: cmd
    main: ./hapesay/main.go
    binary: hapesay
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm
        goarm: 7
  - id: hapethink
    dir: cmd
    main: ./hapethink/main.go
    binary: hapethink
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm
        goarm: 7

archives:
- builds:
  - hapesay
  - hapethink
  name_template: 'hapesay_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE
  - doc/hapesay.1

brews:
- name: hapesay
  tap:
    owner: Rid
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: https://github.com/Rid/hapesay
  description: "Fast, funny, everyone wanted? new hapesay!!"
  folder: Formula
  install: |
    bin.install "hapesay"
    bin.install "hapethink"
    man1.install Dir["doc/hapesay.1"]

nfpms:
  - license: Artistic License 2.0
    maintainer: Rid <rid@cylo.io>
    homepage: https://github.com/Rid/hapesay
    bindir: /usr/local/bin
    description: "Fast, funny, everyone wanted? new hapesay!!"
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: "doc/hapesay.1"
        dst: "/usr/share/man/man1/hapesay.1"

checksum:
  name_template: 'hapesay_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
